config/routes.rb
Build::Application.routes.draw do

  constraints(:host => "broadenandbuild.com") do
    match "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "www.broadenandbuild.com" }.to_s
    }
  end

  devise_for :users, :skip => [:sessions], :controllers => { :registrations => :registrations }
  as :user do
    get 'register' => 'registrations#new', :as => :new_user_registration 
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    match 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session,
      :via => Devise.mappings[:user].sign_out_via
  end

  resources :users
  resources :projects, :only => [:create, :destroy]
  resources :weeks, :only => [:create, :destroy]
  resources :mostimportants, :only => [:create, :destroy]
  resources :journals, :only => [:create, :destroy]
  resources :quotes, :only => [:create, :destroy]
  resources :savors, :only => [:create, :destroy]
  resources :habits, :only => [:create, :destroy]
  resources :improvements, :only => [:create, :destroy]
  resources :needs, :only => [:create, :destroy]
  resources :funs, :only => [:create, :destroy]
  resources :expansions, :only => [:create, :destroy]
  resources :procrastinates, :only => [:create, :destroy]
  resources :procrastinate1s, :only => [:create, :destroy]
  resources :procrastinate2s, :only => [:create, :destroy]
  resources :procrastinate3s, :only => [:create, :destroy]
  resources :gratefuls, :only => [:create, :destroy]
  resources :questions, :only => [:create, :destroy]
  resources :principles, :only => [:create, :destroy]
  resources :results, :only => [:create, :destroy]
  resources :books, :only => [:create, :destroy]
  resources :environments, :only => [:create, :destroy]

  root to: 'static_pages#home'

  get "password_resets/new"

  match '/projects' => 'projects#projects', :via => :get
  match '/weekly' => 'weeks#weekly', :via => :get
  match '/mostimportanttasks' => 'mostimportants#mostimportants', :via => :get
  match '/journals' => 'journals#journals', :via => :get
  match '/quotes' => 'quotes#quotes', :via => :get
  match '/reflect' => 'static_pages#reflect', :via => :get
  match '/agent' => 'static_pages#agent', :via => :get
  match '/funs' => 'funs#funs', :via => :get
  match '/overcomingprocrastination' => 'static_pages#overcomingprocrastination', :via => :get
  match '/gratitude' => 'gratefuls#gratefuls', :via => :get
  match '/questions' => 'questions#questions', :via => :get
  match '/books' => 'books#books', :via => :get
  match '/environments' => 'environments#environments', :via => :get

  match '/savor_the_moment' => 'static_pages#savor', :via => :get
  match '/habits_are_a_choice' => 'static_pages#habits', :via => :get
  match '/self_improvement' => 'static_pages#improvement', :via => :get
  match '/essential_needs' => 'static_pages#needs', :via => :get
  match '/expanding_awareness' => 'static_pages#expand', :via => :get
  match '/shine' => 'static_pages#shine', :via => :get
  match '/goal_setting' => 'static_pages#goals', :via => :get
  match '/donate' => 'static_pages#donate', :via => :get

  match '/help' => 'static_pages#help', :via => :get
  match '/contact' => 'static_pages#contact', :via => :get

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def shine
  end

  def goals
  end

  def june05_challenge
  end

  def donate
  end

  def savor
  end

  def habits
  end

  def improvement
  end

  def needs
  end

  def expand
  end

  def overcomingprocrastination
    if signed_in?
      @procrastinate = Procrastinate.new
      @procrastinationfeed_items = current_user.procrastinationfeed.paginate(:page => params[:page])
      @procrastinate1 = Procrastinate1.new
      @procrastination1feed_items = current_user.procrastination1feed.paginate(:page => params[:page])
      @procrastinate2 = Procrastinate2.new
      @procrastination2feed_items = current_user.procrastination2feed.paginate(:page => params[:page])
      @procrastinate3 = Procrastinate3.new
      @procrastination3feed_items = current_user.procrastination3feed.paginate(:page => params[:page])
    end
  end

  def reflect
    if signed_in?
      @savor = Savor.new
      @savoringfeed_items = current_user.savoringfeed.paginate(:page => params[:page])
      @habit = Habit.new
      @habitualfeed_items = current_user.habitualfeed.paginate(:page => params[:page])
      @improvement = Improvement.new
      @improvingfeed_items = current_user.improvingfeed.paginate(:page => params[:page])
      @need = Need.new
      @needingfeed_items = current_user.needingfeed.paginate(:page => params[:page])
      @expansion = Expansion.new
      @expandingfeed_items = current_user.expandingfeed.paginate(:page => params[:page])
    end
  end

  def agent
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/agent.html.erb
<p>What's your name?</p?
<p>_________'s agent of change</p>

<p>Who do I love?</p>
<p>When do I feel powerful?</p>
<p>What do I enjoy doing?</p>

app/views/static_pages/excellence.html.erb
Pushing Forward Towards Excellence

I began an experiment today focusing on just 5 minute intervals working towards a desired goal I've set for myself.  The jist of it...


Spend 5 minutes working on things I want to improve in my life. Examples for me.

Work on this website.
Exercise.

The main tenets to this exercise are;

Try to get as much quality out of that 5 minutes as I can.
Get in to a creative/productive/resourceful state of mind.

Create a timer that goes off after 5 minutes.
Have people check off the completion of a task.
Have them describe what their method of completion was.
Have them create a finishing exercise to reward their behaviour.

Training Wheels for the Mind: Get started and live in the moment

What do you want to become better/worse at?

What mood state do you want to be in?

Mood (Resourceful, loving, creative, excited, peaceful, optimistic, passionate)
Time (10 sec, 20 sec, 30 sec, 1 min, 2 min, 5 min, 10 min, 20 min, 30 min, 1 hour)
Successes (Ticker that increases)

Action! (Big button)

You succeeded! You completed (time) of being (mood) while (goal).

app/views/static_pages/goals.html.erb
<% provide(:title, 'Goal Setting - Performance vs Mastery') %>
<h1>Mastery vs Performance Goal Setting</h1>

<p>Goal setting doesn't seem to work quite nearly as advertised. It's not just you... almost everyone seems to have the same problem.  Why is that?</p>

<h3>SHINE vs SMART Goals</h3>

<p>Performance goal setting, the "SMART" method... Specific, Measurable, Attainable, Relevant, and Timely, ultimately backfires since it runs in opposition to how we naturally think and motivate ourselves.</p>

<p>The mastery approach on the other hand, "SHINE"... Savor, Habit, Improvement, Need, and Expansion, runs more in line with our natural instincts and strengths.</p>

<p>Mastery goals meet our basic needs of freedom, competence, and connection to others, whereas performance goals feed off our ego and self-esteem. One is focused on the outside world, while the other is directed towards ourselves.</p>

<h3>Humility vs Preserving Self-Esteem</h3>

<p><strong>S-avor</strong>: Enjoying the moments that connect you with others. "I enjoy time with my mother/friend/community." ~ Mastery</p>
<p><strong>M-easurable</strong>: Measuring how you compare to others. "I am winning/dominant/special." ~ Performance</p>

<h3>Realism vs Optimism Mindset</h3>

<p><strong>H-abit</strong>: Choosing which outcomes are under your control. "I can prepare myself for the test/pageant/game." ~ Mastery</p>
<p><strong>T-imely</strong>: When expectations of future events drive your motivation. "I am going to be successful/rewarded/great." ~ Performance</p>

<h3>Improving vs Proving Yourself</h3>

<p><strong>I-mprovement</strong>: What needs to get better. "I am improving my skills/hobbies/relationship." ~ Mastery</p>
<p><strong>A-ttainable</strong>: How you need to be good. "I am intelligent/talented/beautiful." ~ Performance</p>

<h3>Essential vs What's Important</h3>

<p><strong>N-eed</strong>: Which task is essential for a meaningful life. "I need time with my family." ~ Mastery</p>
<p><strong>R-elavant</strong>: Whether the task is important. "I should be with my family." ~ Performance</p>

<h3>Open vs Narrow Minded</h3>

<p><strong>E-xpansion</strong>: Understanding what problem needs to be solved. "What is required to move towards a healthier bodyweight." ~ Mastery</p>
<p><strong>S-pecific</strong>: Deciding how you want to be thinner. "I want to lose 50 lbs of fat." ~ Performance</p>

app/views/static_pages/habits.html.erb
<% provide(:title, 'Habits are a Choice - Effectiveness Though Consistency') %>
<h1>Habits are a Choice</h1>

<p>Every thought we have, thing we do, or feeling we experience in some form is manifested by our habits. They help us by increasing our efficiency so our important resources of energy and attention can be better conserved.</p>

<p>We can choose to either set up positive habits through continually exercising our freedom of choice or let our environment make our decisions for us. It's the difference between being an active verses passive participant in your life!</p>

<p>The word habit unfortunately has a negative connotation for most. Many people see the creating of positive habits as a struggle due to the required self-discipline needed. Conversely attempting to break bad habits can often conjure feelings of self-defeat and failure.</p>

<h3>Enjoyment and Sustainable Improvement</h3>

<p>One of the ways to improve habit making ability is to try to approach it in a more enjoyable manner. Create pleasant change over the long haul rather than opting for fast and painful "instant gratification." Your mind just rebels and begins to shut down.</p>

<p>The more you see actions and thoughts as something you can reasonably sustain over the course of a  lifetime the more likely it will stick. This generally means abandoning the latest fads and quick fix approaches.</p>

<p>It may not be as hyped or sound as exciting but would you rather improve your life or live in a fantasy world where nothing ever changes? Harsh for some people perhaps but if it was easy, everyone would do it right?</p>

<h3>Persistence and Resilience</h3>

<p>A different perspective of habits... rather than trying to exert self-discipline and control, work towards persistence and resilience. Figure out what internally motivates you and against you. It's as simple as... if you get any satisfaction out of what you're doing, you're going to stay with it!</p>

<p>The more you can remain focused on what you want to achieve, enjoy the process, work towards improvement, and making it a priority, the easier it'll be to make a life long habit.</p>

<h3>Brain Injury and Neuroplasticity</h3>

<p>You may have heard the phrase "repetition is the mother of skill." There's no where else this is more evident than the rehabilitation programs created for people with acquired brain injuries.</p>

<p>Some brain injured patients, many who thought were beyond the ability to learn, have displayed an adoption of new habits through diligent repetition and consistency.</p>

<p>Severe aggressive behaviours due to a combination of brain damage, poor coping skills, and dysfunctional childhoods have shown measurable improvement and in many cases complete absence of the previously dysfunctional behavior.

<h3>Repetition Repetition Repetition</h3>

<p>You may not see much change the first time, the 10th time or even the 100th time but gradually the new skill becomes more and more efficient. Often times the biggest obstacle is the belief that the behavior can change.

<p>Once an individual understands it's change is possible, that's when major breakthroughs often occur. Feeling competent in your abilities generally spurs on greater motivation, which then snowballs towards greater improvement.</p>

<h3>Influence from your Environment and Perception</h3>

<p>Our habits are generally triggered by our emotional reaction to what's around us, combined with our perception of what that event means. Familiar people and surroundings can greatly influence specific thought-action tendencies.</p>

<p>That's where the importance of keeping consistency with your environment, social connections, thoughts, and actions can have a great impact on progress. If you know you have a particular weakness towards certain situations, it may be prudent to pick your battles and stay within your limitations... that is until another day when you can chip away at it under safer conditions.</p>

<p>Self-control and discipline require great amounts of "emotional energy" and once that limited supply is temporarily exhausted you're basically powerless to your most basic instincts.</p>

<h3>Fixed vs Growth Mindset</h3>

<p>Fixed vs growth mindsets play a large part in how we perceive our ability to change. If you think your abilities are fixed and unchangeable then you won't put much effort in to trying towards a better life.</p>

<p>However if you believe your abilities are malleable, following effort and learning more efficient strategies, then the road to change will be that much easier.</p>

<h3>Control: The Boundaries of Influence</h3>

<p>Understanding where your control lies, has a large effect on your ability to change. If you believe outside factors determine what you can do or who you are, then improvement will not appear very likely.</p>

<p>Conversely, if you believe you're the master of your destiny - where things under your control can be changed, and those beyond your control can be relinquished, then breakthroughs will be that much easier to develop.</p>

<p><strong>Some Rules of Thumb to Take Control of your Life</strong></p>
<ul>
<p><li> Positively influence your environment so it can influence you back.</li></p>
<p><li> Surround yourself with like minded people.</li></p>
<p><li> Every decision becomes a choice, and through repetition becomes easier with time..</li></p>
</ul>

app/views/static_pages/home.html.erb
<div class="center">
<br>
<br>
<div class="center jumbotron">
  <h1>Broaden and Build</h1>

  <h2>To ignite the human spirit and drive change.</h2>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<% unless ENV['RAILS_ENV'] == "development" %>

<% end %>

app/views/static_pages/hometemp.html.erb
  <div class="center hero-unit">
    <h1>SHINE from Within</h1>

    <h2>Your life is your message to the world. Make sure it's inspiring.</h2>

    <%= link_to "Sign up now!", new_user_registration_path, 
                                class: "btn btn-large btn-primary" %>

<div class="space"></div>

<div class="homemarginleft">

  <p><strong>S-avor</strong>: Connecting positive emotions, to reenergizing activities and people.</p>
			      
  <p><strong>H-abit</strong>: Effectively managing attention, through paths of least resistance.</p>
			      
  <p><strong>I-mprovement</strong>: Building skills, to successfully impact one's environment.</p>
									        
  <p><strong>N-eed</strong>: Prioritizing essential needs, to direct long term well-being.</p>

  <p><strong>E-xpansion</strong>: Broadening awareness, to factors within one's control.</p>

</div>
  </div>

app/views/static_pages/improvement.html.erb
<% provide(:title, 'Self Improvement - Deliberate Practice') %>
<h1>Would you Rather Improve or Prove Yourself?</h1>

<p>One of the main reasons people are drawn to personal development, is to improve their useful knowledge, skills, and abilities to positively frame the world around them. If a practical skill set improves the quality of your life and others, greater personal freedoms and relationships are more able to flourish.</p>

<p>Strangely, the self-improvement industry appears to be at ends with it's original intent. Much of it isn't about actual improvement, rather than making you feel comfortable and right within yourself.</p>

<p>While managing your emotions is of course valuable, lets not disguise this advise for what it really is. There's coping with the emotional fallout of life's "struggles", and then there's working past them to more positive ground. If the only thing we're doing is protecting people's self-esteem then how valuable is it really?</p>

<h3>Self-Esteem or Self-Improvement</h3>

<p>There's a disturbing trend cultivating in western culture - to protect people's self-worth and confidence at the expense of being more competent. This idea is especially dominant in the manner we educate our children, and the political correctness we adults portray as a society.</p>

<p>Labelling a person as intelligent, beautiful, or special (whether it's true or not), may serve to temporarily boost one's confidence, however not without it's share of negative consequences. If someone identifies themselves based upon a generalization, a perceived value of worth tends to emerge.</p>

<p>A strong motivating force to prove their ability, balances an avoidance to feel like a personal failure. The goal becomes not to <strong>improve</strong> your intelligence, only to <strong>feel</strong> intelligent.  These people will tend to seek out opportunities that validate their self-concept and avoid situations where expectations of success may appear low.</p>

<p>The resulting outcome becomes fragile self-esteem locked in a bubble of perceived competency. They are only happy when they succeed to validate themselves, and become depressed or anxious when these conditions aren't met.</p>

<h3>Being Good vs Getting Better</h3>

<p>When choosing to work on getting better at the expense of appearing good, a whole world of opportunity can begin to develop. One focuses on what needs to be done, rather than what drives their immediate emotions.</p>

<p>It becomes easier to live in the moment and enjoy what you're doing, rather than being preoccupied about past failures or future expectations. An interesting side effect then begins to occur... Even though it may not be your primary intention, others begin to hold much more value to your daily contributions. You focus on creating happiness outside yourself rather than how things directly benefit you.</p>

<p>Permanently perceived failures, loses, and punishments start being viewed as temporary obstacles, challenges, and detours. Difficulty becomes associated to specific situations rather than generalized to your life as a whole.</p>

<p>Emotional stability becomes easier to maintain, due to not having to justify to yourself why things didn't work out as expected.</p>

<h3>Mastery vs Performance Goal Setting</h3>

<p>The concept of ego and humility falls within the dichotomy of mastery oriented goal setting vs the more traditional SMART performance goal setting method. If you've ever wondered why goal setting has been so difficult up to this point a different perspective may be in order.</p>

<p>Living in the moment, enjoying what you do, and continually improving provides much less resistance to getting things done and living on a much more satisfying level.</p>

app/views/static_pages/june05_challenge.html.erb
<% provide(:title, 'Creating Focus and Overcoming Procrastination') %>
<h1>Creating Focus and Overcoming Procrastination<h1>

<h3>Challenge - June 5, 2012</h3>

<p>To create something of enough value today, to inspire a small donation.</p>

<p>Started 10:22 AM EST. Deadline midnight.</p>

<p>What would inspire someone to donate $10? How can I create that value?</p>

<p>How do I use my skills and strengths to create something that emotionally resonates with people, and benefits them in some way?</p>

<h3>Plan</h3>

<p>Create idea - By 11:22 AM (Finished 11:12 AM)</p>

<p>Finish article or app - By 2 pm (Finished 2:09 PM)</p>

<p>Set up donation system through Paypal - By 3 pm (Finished 3:06 PM)</p>

<p>Market through blogs and social marketing - Until 5 pm or more appropriate deadline.</p>

<h3>Idea</h3>

<p>Complete something to positively impact a life today, that promotes the paying of it forward.</p>

<p><strong>1.</strong> Share your appreciation with someone, who deserves but may not be fully aware, of their positive impact on your life.</p>

<p><strong>2.</strong> Do something that provides great satisfaction; a hobby, interest or friendship you may have lost touch with from the past.</p>

<p><strong>3.</strong> Anything else that invigorates and makes you feel alive. Be creative are share your idea!</p>

<p>The kicker: Post your story and help inspire others. The value is in following through today; to make positive change, create inspiration, and contribute to yours and other's happiness.</p>

<%= render :partial => 'shared/disqus' %>

<p>If you received considerable value today, please consider a <%= link_to 'donation', donate_path %>. My goal is to provide something of worth, people will voluntarily pay for. It also provides useful feedback and inspiration towards greater value!</p>

<p>I'll provide an update at the end of the day to share my learning experiences from this exercise. The primary goal isn't necessarily to receive a donation but to follow through with an attempt at quality, with concentrated effort, in a relatively short period of time. All areas of improvement I need to focus on. :)</p>

app/views/static_pages/letter_dad.html.erb
Since I created this exercise, it's only appropriate I start it off as well.

Most families have their dysfunctional elements. My father and I haven't had the closest relationship over the years, which is why I decided to share the things I appreciate most from our relationship. Here's is the letter I emailed him.

"Hi Dad,

I know we don't talk much about feelings or emotional events in general, usually sticking to politics, the economy, or health related stuff. However as I've gotten older, it appears easier to perhaps see things from your perspective. Possibly because I'm getting older and having to go through similar life events you've once had to go through or being that we have similar personalities, I'm not sure.

I've noticed for myself, when going through difficulties I can often get caught up in self-preservation, usually at the expense of my relationships. It can be hard to focus on helping others when more pressing personal needs are at stake.

It seems the older I get the more similarities I tend to see between us, which probably means you also understand me to a greater degree than most people. One of the characteristics I've most admired, is your ability to be non-judgemental through many of the hardships I've undergone. Whether it was temporarily dropping out of university and changing majors, break-ups with girlfriends or pursuing self-employment, you've been supportive throughout everything and I appreciate it.

My struggles with depression alongside your own, and the perspective it's given me on the whole I believe, has given me a greater appreciation for the times you've been there for me. I wanted to let you know how positively our relationship has impacted me, and that you've done right by me as a father.

Love Brian"

Letters like that kind be emotionally difficult to write not to mention pressing send afterwards! :)

app/views/static_pages/oracle.html.erb
The Co-op business model:share whatever you've got.

Where do you start when making any important life change?

Ahhh... The million dollar question.

This is the place where I've always had difficulty making progress. What should I be focusing on? What should I be doing? How do I get motivated? What will make it stick?

I've had the habit of reading, reading, and more reading... collecting more information. Paralysis by analysis. Gah!!!

The process gets overwhelming and frustrating. I get overloaded with stress... Things fall apart and I start at ground once zero again.

The dimensions of a powerful question.

Is thought-provoking and invites reflection and finding deeper meaning
Expands possibilities or focuses attention
Brings underlying assumptions to light
Stimulates curiosity and creativity
Can help a group move forward

Less Powerful Questions
Yes/no
Which
Who
When
Where
What
How
Why*
What If
More Powerful Questions


“When do you go running?”

    “When the time is right.” 

“When is the time right?”

    “When it's a nice day, and I've finished my work, and I haven't just eaten, and I'm feeling energetic.” 

“Repeat that last sentence, changing ‘and’ to ‘or’.”

    “When it's a nice day, OR I've finished my work, OR I haven't just eaten, OR I'm feeling energetic.” 

“That sounds like a better plan.”

Mythical Figure of Wisdom

People can ask questions and sage will respond in a manner appropriate to best enlighten individual.

Keep a record of dialogue on the computer.

<h1>Consult the Oracle</h1>

Picture of Oracle

<h3>What do you need help with?</h3>

Is thought-provoking and invites reflection and finding deeper meaning
Expands possibilities or focuses attention
Brings underlying assumptions to light
Stimulates curiosity and creativity
Can help you move forward

Promotes action and prevents procrastination
Enhances self discovery
Establishes priorities and focuses attention

Hence the definition can be 'a resource for everyday life, not the objective of living. It is a positive concept emphasizing personal and collective resources, as well as physical and mental capacities.'

What is your health quotient?

Physical Health: Energy, ability to resist disease, skill aquisition

Social Health: Charisma, aesthetics, ability to advance relationships

Mental Health: Intelligence, wisdom, ability to resist stress (will-power), focus/attention, organization/prioritization

app/views/static_pages/overcomingprocrastination.html.erb
<% provide(:title, 'Overcoming Procrastination') %>

<h1>Overcoming Procrastination</h1>

<table>
  <tr>
    <td>

<p>What am I procrastinating?</p>

      <%= render 'shared/procrastinate_form' %>
      <%= render 'shared/procrastinationfeed' %>

<div class="space"></div>

<p>What pain will procrastination cause me later, instead of the temporary comfort/pleasure it will give me now?</p>

      <%= render 'shared/procrastinate1_form' %>
      <%= render 'shared/procrastination1feed' %>

<div class="space"></div>

<p>Who is the person I want to be, and the life I want to live? Including my intentions to do the good work I think I should do.</p>

      <%= render 'shared/procrastinate2_form' %>
      <%= render 'shared/procrastination2feed' %>

<div class="space"></div>

<p>What urges do I commonly encounter that distracts me from the real things I want to do? Bring them out in to the open so I can be more actively aware.</p>

      <%= render 'shared/procrastinate3_form' %>
      <%= render 'shared/procrastination3feed' %>

<div class="space"></div>

<p>Smile, breathe, and let go.</p>

<p>Take one step, and become the person I want to be.</p>

    </td>
  </tr>
</table>

<h2>‘You can only lose what you cling to.’ ~Buddha</h2>

app/views/static_pages/principles.html.erb
Goals (wanting to improve) are not consistent with contentment (being happy with where you are).

Instead of working with a fixed outcome (goal), work from moment to moment, using principles that work for you. Each moment, don’t ask “am I doing something to move me to my goal?” but instead ask, “Am I doing something right now that’s based on one of my values or principles?”

ask, “Am I doing something right now that’s based on one of my values or principles?”

Four Principles


Love what you do. This seems obvious, but so often people do things that they’re not excited about. I try to find things that I love doing, and if there’s some mundane task I have to do for some reason, I either eliminate it or find a way to enjoy the hell out of it.

Help others. I am strongly motivated by the desire to do things that will help people — my readers, my friends, my kids, people in need. And so this principle guides everything I do, including all of my writing. I highly recommend it.

Build relationships & trust. Each thing you do, personally and for your business, should be building a relationship. I build relationships with my readers by being authentic and trying my best to help, and build relationships with friends & family in the same way. Being trustworthy as much as humanly possible is a great way to build relationships, so these two go hand-in-hand.

Be curious. When you’re curious about other people, and about life in general, you tend to be a better listener, a better friend, more informed, and have fun each step along the way.

You have to open your mind to going places you never expected to go. If you live without goals, you’ll explore new territory. You’ll learn some unexpected things. You’ll end up in surprising places. That’s the beauty of this philosophy, but it’s also a difficult transition.

Always remember: the journey is all. The destination is beside the point.

‘A good traveller has no fixed plans, and is not intent on arriving.’ ~Lao Tzu